$axure.loadCurrentPage({
  "url":"core_1__getting_started.html",
  "generationDate":new Date(1413014262026.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cfa283922d494a5ab728274b30319f94",
    "type":"Axure:Page",
    "name":"CORE 1: Getting Started",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFAFAFA},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9c8eac15cee34ddb9934540497423c5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":334},
            "size":{
              "width":220,
              "height":157},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a807f16ddef5417c95501559faec4417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":334},
                "size":{
                  "width":220,
                  "height":157},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u0.png"}},
{
          "id":"2c52ef131e1c49a0b3222215dab062a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":12},
            "size":{
              "width":217,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d795c8f84f7147fea33985668fa98a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":395,
                  "y":12},
                "size":{
                  "width":217,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u2.jpg"}},
{
          "id":"c3107d5c5da6448da0abe1c927466917",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":937},
            "size":{
              "width":428,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d491d611e2c64ee98760241409311e1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":937},
                "size":{
                  "width":428,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u4.jpg"}},
{
          "id":"1e48972cc668414486d4325857d7241a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"15px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":49,
              "y":255},
            "size":{
              "width":180,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b423aacf3bb4dc399a9dd75b549660d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"15px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":49,
                  "y":255},
                "size":{
                  "width":180,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"474c0305029746438296a86b119db02b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":279,
              "y":255},
            "size":{
              "width":157,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"477715f7cceb4d4891b8407499e950b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":279,
                  "y":255},
                "size":{
                  "width":157,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f654fb5d48044216b9c1ffa133fb3d54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":488,
              "y":256},
            "size":{
              "width":148,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87f01185399241b7a8b6e18cc69fa5fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":488,
                  "y":256},
                "size":{
                  "width":148,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"947500935cf34919879408e7f115beb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":258,
              "y":534},
            "size":{
              "width":225,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf54972bb7fb4e5e8bed6654ff1ccf1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":534},
                "size":{
                  "width":225,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"feb6dfca06684d63b738dad605ad79a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"15px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":49,
              "y":744},
            "size":{
              "width":307,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c93164666e8744dbb863943f37d623fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"15px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":49,
                  "y":744},
                "size":{
                  "width":307,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2208439a24b44caeba31c6f080128ed0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Nexa Light'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "lineSpacing":"40px",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":25,
              "y":84},
            "size":{
              "width":339,
              "height":85},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"429058fd2de94a85b20992737615077c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Nexa Light'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "lineSpacing":"40px",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":25,
                  "y":84},
                "size":{
                  "width":339,
                  "height":85},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u16.png"}},
{
          "id":"e9a9b82fbb3446f49e409e2968c29569",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"15px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":399,
              "y":744},
            "size":{
              "width":281,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03f14eb9a5154b16ab6c05f8f750e711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"15px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":744},
                "size":{
                  "width":281,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2110aa648e440e49e6f5c2c9f7d02a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "opacity":"0.8"}},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "location":{
              "x":20,
              "y":1028},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d042f8ecf4a54c9ea33a4b84a3f969d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"0.8"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "location":{
                  "x":20,
                  "y":1028},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open http://www.axure.com/learn/core/pages?src=gs in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://www.axure.com/learn/core/pages?src=gs",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/core_1__getting_started/u20.png",
            "mouseOver~":"images/core_1__getting_started/u20.png"}},
{
          "id":"584968e258434856953fc4cd16108b14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":20,
              "y":255},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f272887b634b4a96a33f496337617a53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":20,
                  "y":255},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u22.png"}},
{
          "id":"e1342ce405814dffbb475356d9db0c09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":737},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed327e7d4aee4588951d81413aae9e0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":737},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u24.png"}},
{
          "id":"f6b3db86960f40f6a636be5ce4a3b561",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":734},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b5371a0bdb14026aa6d1ce02f3463de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":734},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u26.png"}},
{
          "id":"54b1327175a244f7a52d40c7e1942340",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":522},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3fdb438ed74e3488a5c4495dc1675c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":522},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u28.png"}},
{
          "id":"c59aa539b4af432d81ccd71ff9bb1637",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":246},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85f9da65bf046aead9484ab781d0e32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":246},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u30.png"}},
{
          "id":"a916c47ed32f45e08caeff47eb318d43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":732},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67b95f7c98a6416286c89185383b8b38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":732},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u32.png"}},
{
          "id":"b58fb3a6f4d045929f70f28cbdd396e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":242},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7685c70c7bc4e86a6595fa4697890a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":242},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u34.png"}},
{
          "id":"505a0a3aa50c41cfaf416222430cf337",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":20},
            "size":{
              "width":147,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea33bb70c3c4fd0b6751da71cb46dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":20},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u36.png"}},
{
          "id":"4d2003eeec934a58a89fee30f67901a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":250,
              "y":255},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b9ff80801e14cceb5f027eec0793bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":250,
                  "y":255},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u22.png"}},
{
          "id":"afa7cfd572f74a168462e0fd13cb8143",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":228,
              "y":534},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e4661facd6840d58eb7e488ca7cccc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":228,
                  "y":534},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u22.png"}},
{
          "id":"ec71ea6716504a29bdf976c43a925274",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":460,
              "y":255},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b5c7c0378046819e26896a35e6522a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":460,
                  "y":255},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u22.png"}},
{
          "id":"4f228946536a44adba70bfd3e51744c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":20,
              "y":744},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8048cb195ef492387110e76d4830f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":20,
                  "y":744},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u22.png"}},
{
          "id":"a7abe25bfca04a94ad11670a61715c62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Nexa Light'",
            "fontSize":"24px",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "lineSpacing":"26px",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":135,
              "y":646},
            "size":{
              "width":430,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7405a6bbd29d47dd9a81b3a807d8f4ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Nexa Light'",
                "fontSize":"24px",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "lineSpacing":"26px",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":135,
                  "y":646},
                "size":{
                  "width":430,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u46.png"}},
{
          "id":"fbb16f7c469b41b68d3cc958f0a7b3cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB2184},
            "location":{
              "x":366,
              "y":744},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ccacb5d7a9430dbd8036252b8e3dbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB2184},
                "location":{
                  "x":366,
                  "y":744},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u22.png"}},
{
          "id":"034b66bc197e4ef78e4d1b2fa9642b44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Nexa Light'",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":20,
              "y":912},
            "size":{
              "width":318,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af56a2d68a234f5e92138be03c254ddf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Nexa Light'",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":20,
                  "y":912},
                "size":{
                  "width":318,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u50.png"}},
{
          "id":"bc603264492147f4bf263cbc6bdef92b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":879},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/core_1__getting_started/u52_line.png"}},
{
          "id":"92472f2c87594b0ca4108e75aca67e9f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1150},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/core_1__getting_started/u52_line.png"}},
{
          "id":"b45b3494bdce41cea106fcf2ae355948",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":255},
            "size":{
              "width":76,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d95630fae8bb455eb64cb72bc861df6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":524,
                  "y":255},
                "size":{
                  "width":76,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u54.png"}},
{
          "id":"0b63b4e80f7841aebfbd61cb33571dae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":396},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724e470121b7457a95b3c7c8558d8ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":396},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u56.png"}},
{
          "id":"627c68b53b1f45c59475afd68585fbc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Nexa Light'",
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "lineSpacing":"26px",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":23,
              "y":196},
            "size":{
              "width":591,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b914bba4f2a14695a8f4124ecf75fbbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Nexa Light'",
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "lineSpacing":"26px",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":23,
                  "y":196},
                "size":{
                  "width":591,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u58.png"}},
{
          "id":"28e4ab5f457e4d34beb94dfc697543ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":95,
              "y":441},
            "size":{
              "width":70,
              "height":48},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEB2184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93fdd90fb835412fa83aaccc76d3ecaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":95,
                  "y":441},
                "size":{
                  "width":70,
                  "height":48},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEB2184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u60.png"}},
{
          "id":"ca71dfebe34c43c88741657f429b492b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":435},
            "size":{
              "width":152,
              "height":10},
            "rotation":"339",
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEB2184}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/core_1__getting_started/u62_end.png",
            "line~":"images/core_1__getting_started/u62_line.png"}},
{
          "id":"e419f2b8341444228d23521bf7fe5ccc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":334},
            "size":{
              "width":213,
              "height":115},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e473249a0c5d49fa8b9d5183795f922f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":334},
                "size":{
                  "width":213,
                  "height":115},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u63.png"}},
{
          "id":"28b967a3ab1a47238fe0a744a5aa064e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":520,
              "y":406},
            "size":{
              "width":71,
              "height":19},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEB2184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1793af67f5f4ca0802b20efa87a357f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":520,
                  "y":406},
                "size":{
                  "width":71,
                  "height":19},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEB2184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/core_1__getting_started/u65.png"}},
{
          "id":"21e46bd7a8f74120b3d7a3d2bc4914fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":422,
              "y":70},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff715436a8b413ba9a18780002aa0a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":422,
                  "y":70},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open CORE 1: Getting Started in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"core_1__getting_started.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/core_1__getting_started/u67.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9c8eac15cee34ddb9934540497423c5f":{
      "scriptId":"u0"},
    "a807f16ddef5417c95501559faec4417":{
      "scriptId":"u1"},
    "2c52ef131e1c49a0b3222215dab062a8":{
      "scriptId":"u2"},
    "d795c8f84f7147fea33985668fa98a89":{
      "scriptId":"u3"},
    "c3107d5c5da6448da0abe1c927466917":{
      "scriptId":"u4"},
    "d491d611e2c64ee98760241409311e1c":{
      "scriptId":"u5"},
    "1e48972cc668414486d4325857d7241a":{
      "scriptId":"u6"},
    "5b423aacf3bb4dc399a9dd75b549660d":{
      "scriptId":"u7"},
    "474c0305029746438296a86b119db02b":{
      "scriptId":"u8"},
    "477715f7cceb4d4891b8407499e950b7":{
      "scriptId":"u9"},
    "f654fb5d48044216b9c1ffa133fb3d54":{
      "scriptId":"u10"},
    "87f01185399241b7a8b6e18cc69fa5fc":{
      "scriptId":"u11"},
    "947500935cf34919879408e7f115beb5":{
      "scriptId":"u12"},
    "bf54972bb7fb4e5e8bed6654ff1ccf1f":{
      "scriptId":"u13"},
    "feb6dfca06684d63b738dad605ad79a4":{
      "scriptId":"u14"},
    "c93164666e8744dbb863943f37d623fc":{
      "scriptId":"u15"},
    "2208439a24b44caeba31c6f080128ed0":{
      "scriptId":"u16"},
    "429058fd2de94a85b20992737615077c":{
      "scriptId":"u17"},
    "e9a9b82fbb3446f49e409e2968c29569":{
      "scriptId":"u18"},
    "03f14eb9a5154b16ab6c05f8f750e711":{
      "scriptId":"u19"},
    "b2110aa648e440e49e6f5c2c9f7d02a7":{
      "scriptId":"u20"},
    "d042f8ecf4a54c9ea33a4b84a3f969d6":{
      "scriptId":"u21"},
    "584968e258434856953fc4cd16108b14":{
      "scriptId":"u22"},
    "f272887b634b4a96a33f496337617a53":{
      "scriptId":"u23"},
    "e1342ce405814dffbb475356d9db0c09":{
      "scriptId":"u24"},
    "ed327e7d4aee4588951d81413aae9e0b":{
      "scriptId":"u25"},
    "f6b3db86960f40f6a636be5ce4a3b561":{
      "scriptId":"u26"},
    "5b5371a0bdb14026aa6d1ce02f3463de":{
      "scriptId":"u27"},
    "54b1327175a244f7a52d40c7e1942340":{
      "scriptId":"u28"},
    "7c3fdb438ed74e3488a5c4495dc1675c":{
      "scriptId":"u29"},
    "c59aa539b4af432d81ccd71ff9bb1637":{
      "scriptId":"u30"},
    "d85f9da65bf046aead9484ab781d0e32":{
      "scriptId":"u31"},
    "a916c47ed32f45e08caeff47eb318d43":{
      "scriptId":"u32"},
    "67b95f7c98a6416286c89185383b8b38":{
      "scriptId":"u33"},
    "b58fb3a6f4d045929f70f28cbdd396e2":{
      "scriptId":"u34"},
    "d7685c70c7bc4e86a6595fa4697890a7":{
      "scriptId":"u35"},
    "505a0a3aa50c41cfaf416222430cf337":{
      "scriptId":"u36"},
    "fea33bb70c3c4fd0b6751da71cb46dd5":{
      "scriptId":"u37"},
    "4d2003eeec934a58a89fee30f67901a8":{
      "scriptId":"u38"},
    "7b9ff80801e14cceb5f027eec0793bcd":{
      "scriptId":"u39"},
    "afa7cfd572f74a168462e0fd13cb8143":{
      "scriptId":"u40"},
    "3e4661facd6840d58eb7e488ca7cccc8":{
      "scriptId":"u41"},
    "ec71ea6716504a29bdf976c43a925274":{
      "scriptId":"u42"},
    "38b5c7c0378046819e26896a35e6522a":{
      "scriptId":"u43"},
    "4f228946536a44adba70bfd3e51744c7":{
      "scriptId":"u44"},
    "d8048cb195ef492387110e76d4830f0d":{
      "scriptId":"u45"},
    "a7abe25bfca04a94ad11670a61715c62":{
      "scriptId":"u46"},
    "7405a6bbd29d47dd9a81b3a807d8f4ae":{
      "scriptId":"u47"},
    "fbb16f7c469b41b68d3cc958f0a7b3cd":{
      "scriptId":"u48"},
    "25ccacb5d7a9430dbd8036252b8e3dbd":{
      "scriptId":"u49"},
    "034b66bc197e4ef78e4d1b2fa9642b44":{
      "scriptId":"u50"},
    "af56a2d68a234f5e92138be03c254ddf":{
      "scriptId":"u51"},
    "bc603264492147f4bf263cbc6bdef92b":{
      "scriptId":"u52"},
    "92472f2c87594b0ca4108e75aca67e9f":{
      "scriptId":"u53"},
    "b45b3494bdce41cea106fcf2ae355948":{
      "scriptId":"u54"},
    "d95630fae8bb455eb64cb72bc861df6e":{
      "scriptId":"u55"},
    "0b63b4e80f7841aebfbd61cb33571dae":{
      "scriptId":"u56"},
    "724e470121b7457a95b3c7c8558d8ce3":{
      "scriptId":"u57"},
    "627c68b53b1f45c59475afd68585fbc1":{
      "scriptId":"u58"},
    "b914bba4f2a14695a8f4124ecf75fbbb":{
      "scriptId":"u59"},
    "28e4ab5f457e4d34beb94dfc697543ae":{
      "scriptId":"u60"},
    "93fdd90fb835412fa83aaccc76d3ecaa":{
      "scriptId":"u61"},
    "ca71dfebe34c43c88741657f429b492b":{
      "scriptId":"u62"},
    "e419f2b8341444228d23521bf7fe5ccc":{
      "scriptId":"u63"},
    "e473249a0c5d49fa8b9d5183795f922f":{
      "scriptId":"u64"},
    "28b967a3ab1a47238fe0a744a5aa064e":{
      "scriptId":"u65"},
    "f1793af67f5f4ca0802b20efa87a357f":{
      "scriptId":"u66"},
    "21e46bd7a8f74120b3d7a3d2bc4914fc":{
      "scriptId":"u67"},
    "0ff715436a8b413ba9a18780002aa0a6":{
      "scriptId":"u68"}}});